// frontend/src/utils/business/serviceLibrary.js

/*
  =========================================================
  SERVIDIAL MASTER SERVICE LIBRARY
  =========================================================

  Purpose:
  - Large searchable service vocabulary
  - Used as fallback / common service suggestions
  - Category-specific suggestions remain in serviceConfig.js
  - Users can still create custom services
  - Keep service names short, searchable and business-friendly

  IMPORTANT:
  Do not put category-specific ranking logic here.
  This file is only the master service vocabulary.
*/

export const SERVICE_LIBRARY = [

  // =======================================================
  // GENERAL BUSINESS SERVICES
  // =======================================================

  "Consultation",
  "Installation",
  "Repair",
  "Maintenance",
  "Inspection",
  "Replacement",
  "Upgrade",
  "Servicing",
  "Cleaning",
  "Testing",
  "Diagnosis",
  "Design",
  "Planning",
  "Setup",
  "Customization",
  "Modification",
  "Restoration",
  "Renovation",
  "Emergency Service",
  "On Site Service",
  "Home Service",
  "Doorstep Service",
  "Pickup Service",
  "Delivery Service",
  "Annual Maintenance",
  "Preventive Maintenance",
  "Same Day Service",
  "Express Service",
  "24 Hour Service",
  "Installation & Setup",
  "Repair & Maintenance",
  "Sales & Service",

  // =======================================================
  // ELECTRICAL SERVICES
  // =======================================================

  "Electrical Installation",
  "Electrical Repair",
  "Electrical Maintenance",
  "Electrical Inspection",
  "Electrical Testing",
  "Electrical Wiring",
  "House Wiring",
  "Commercial Wiring",
  "Industrial Wiring",
  "Concealed Wiring",
  "Open Wiring",
  "Rewiring",
  "New Wiring",
  "Switch Board Installation",
  "Switch Board Repair",
  "Switch Replacement",
  "Socket Installation",
  "Socket Repair",
  "MCB Installation",
  "MCB Replacement",
  "MCB Repair",
  "RCCB Installation",
  "RCCB Replacement",
  "DB Installation",
  "Distribution Board Installation",
  "Electrical Panel Installation",
  "Electrical Panel Repair",
  "Fuse Replacement",
  "Fuse Repair",
  "Circuit Repair",
  "Short Circuit Repair",
  "Power Failure Repair",
  "Earthing Installation",
  "Earthing Testing",
  "Earthing Repair",
  "Meter Installation",
  "Meter Replacement",
  "Meter Connection",
  "Electric Meter Repair",
  "Load Extension",
  "New Electricity Connection",
  "Electrical Load Testing",
  "Light Installation",
  "Light Repair",
  "LED Light Installation",
  "LED Light Replacement",
  "Tube Light Installation",
  "Tube Light Repair",
  "Chandelier Installation",
  "Decorative Lighting",
  "Outdoor Lighting",
  "Garden Lighting",
  "Security Light Installation",
  "Sensor Light Installation",
  "Fan Installation",
  "Fan Repair",
  "Ceiling Fan Repair",
  "Exhaust Fan Repair",
  "Table Fan Repair",
  "Fan Capacitor Replacement",
  "Fan Regulator Replacement",
  "Inverter Installation",
  "Inverter Repair",
  "Inverter Battery Replacement",
  "UPS Installation",
  "UPS Repair",
  "Generator Installation",
  "Generator Repair",
  "Generator Maintenance",
  "Solar Panel Installation",
  "Solar Inverter Installation",
  "Solar System Maintenance",
  "Electrical Safety Inspection",

  // =======================================================
  // PLUMBING SERVICES
  // =======================================================

  "Plumbing Installation",
  "Plumbing Repair",
  "Plumbing Maintenance",
  "Emergency Plumbing",
  "Pipe Installation",
  "Pipe Fitting",
  "Pipe Replacement",
  "Pipe Repair",
  "Water Pipe Installation",
  "Water Pipe Repair",
  "Drain Pipe Installation",
  "Drain Pipe Repair",
  "PVC Pipe Fitting",
  "CPVC Pipe Fitting",
  "UPVC Pipe Fitting",
  "GI Pipe Fitting",
  "Copper Pipe Fitting",
  "Tap Installation",
  "Tap Repair",
  "Tap Replacement",
  "Mixer Tap Installation",
  "Mixer Tap Repair",
  "Shower Installation",
  "Shower Repair",
  "Wash Basin Installation",
  "Wash Basin Repair",
  "Sink Installation",
  "Sink Repair",
  "Kitchen Sink Installation",
  "Bathroom Plumbing",
  "Bathroom Repair",
  "Toilet Installation",
  "Toilet Repair",
  "Toilet Replacement",
  "Flush Repair",
  "Flush Tank Repair",
  "Water Tank Installation",
  "Water Tank Cleaning",
  "Water Tank Repair",
  "Water Tank Connection",
  "Motor Installation",
  "Water Pump Installation",
  "Water Pump Repair",
  "Booster Pump Installation",
  "Drainage Cleaning",
  "Drain Cleaning",
  "Blocked Drain Repair",
  "Sewer Line Repair",
  "Sewer Cleaning",
  "Leak Detection",
  "Water Leakage Repair",
  "Bathroom Leakage Repair",
  "Roof Water Leakage Repair",
  "Gas Pipe Installation",
  "Plumbing Inspection",

  // =======================================================
  // AIR CONDITIONER / HVAC
  // =======================================================

  "AC Installation",
  "AC Repair",
  "AC Servicing",
  "AC Maintenance",
  "AC Gas Filling",
  "AC Gas Refilling",
  "AC Gas Leakage Repair",
  "AC Cleaning",
  "AC Deep Cleaning",
  "AC Filter Cleaning",
  "AC Coil Cleaning",
  "AC Compressor Repair",
  "AC Compressor Replacement",
  "AC PCB Repair",
  "AC PCB Replacement",
  "AC Capacitor Replacement",
  "AC Fan Motor Repair",
  "AC Fan Motor Replacement",
  "AC Drain Pipe Cleaning",
  "AC Drainage Repair",
  "AC Cooling Repair",
  "AC Installation & Uninstallation",
  "Split AC Installation",
  "Window AC Installation",
  "Cassette AC Installation",
  "Central AC Installation",
  "Duct AC Installation",
  "Duct Cleaning",
  "HVAC Installation",
  "HVAC Repair",
  "HVAC Maintenance",
  "Air Cooler Repair",
  "Air Cooler Servicing",
  "Air Purifier Service",
  "Ventilation Installation",
  "Exhaust System Installation",

  // =======================================================
  // CARPENTRY
  // =======================================================

  "Carpentry Service",
  "Furniture Repair",
  "Furniture Polishing",
  "Furniture Restoration",
  "Wood Repair",
  "Wood Polishing",
  "Wooden Furniture Making",
  "Custom Furniture",
  "Custom Cabinet Making",
  "Wardrobe Making",
  "Modular Wardrobe",
  "Kitchen Cabinet Making",
  "Modular Kitchen Installation",
  "Wooden Door Making",
  "Door Repair",
  "Door Installation",
  "Door Polishing",
  "Door Lock Installation",
  "Window Repair",
  "Window Installation",
  "Wooden Window Making",
  "Bed Making",
  "Sofa Frame Repair",
  "Table Making",
  "Chair Making",
  "Shelf Installation",
  "Wall Shelf Installation",
  "TV Unit Making",
  "Study Table Making",
  "Office Furniture Making",
  "Wooden Partition",
  "False Ceiling Woodwork",
  "Wooden Flooring",
  "Wooden Panel Installation",
  "Wood Cutting",
  "Wood Carving",

  // =======================================================
  // PAINTING
  // =======================================================

  "House Painting",
  "Interior Painting",
  "Exterior Painting",
  "Wall Painting",
  "Ceiling Painting",
  "Room Painting",
  "Office Painting",
  "Commercial Painting",
  "Industrial Painting",
  "Texture Painting",
  "Designer Wall Painting",
  "Stencil Painting",
  "Spray Painting",
  "Wood Painting",
  "Metal Painting",
  "Gate Painting",
  "Door Painting",
  "Waterproof Painting",
  "Waterproof Coating",
  "Wall Waterproofing",
  "Roof Waterproofing",
  "Terrace Waterproofing",
  "Damp Proofing",
  "Wall Putty",
  "POP Work",
  "Wall Repair",
  "Crack Repair",
  "Color Consultation",

  // =======================================================
  // CLEANING SERVICES
  // =======================================================

  "Home Cleaning",
  "House Cleaning",
  "Deep Home Cleaning",
  "Office Cleaning",
  "Commercial Cleaning",
  "Industrial Cleaning",
  "Bathroom Cleaning",
  "Kitchen Cleaning",
  "Bedroom Cleaning",
  "Living Room Cleaning",
  "Floor Cleaning",
  "Window Cleaning",
  "Glass Cleaning",
  "Sofa Cleaning",
  "Carpet Cleaning",
  "Mattress Cleaning",
  "Curtain Cleaning",
  "Chair Cleaning",
  "Dining Table Cleaning",
  "Water Tank Cleaning",
  "Overhead Tank Cleaning",
  "Underground Tank Cleaning",
  "Toilet Cleaning",
  "Kitchen Chimney Cleaning",
  "Exhaust Fan Cleaning",
  "AC Cleaning",
  "Floor Scrubbing",
  "Floor Polishing",
  "Marble Polishing",
  "Granite Polishing",
  "Tile Cleaning",
  "Tile Polishing",
  "Move In Cleaning",
  "Move Out Cleaning",
  "Post Construction Cleaning",
  "Post Renovation Cleaning",
  "Event Cleaning",
  "Restaurant Cleaning",
  "Hotel Cleaning",
  "Sanitization Service",
  "Disinfection Service",
  "Steam Cleaning",

  // =======================================================
  // PEST CONTROL
  // =======================================================

  "Pest Control",
  "Cockroach Control",
  "Ant Control",
  "Bed Bug Control",
  "Mosquito Control",
  "Termite Control",
  "Rat Control",
  "Rodent Control",
  "House Fly Control",
  "Fly Control",
  "Lizard Control",
  "Flea Control",
  "Tick Control",
  "Silverfish Control",
  "Spider Control",
  "Wasp Control",
  "Bee Control",
  "Wood Borer Control",
  "Moth Control",
  "Stored Grain Pest Control",
  "Commercial Pest Control",
  "Residential Pest Control",
  "Industrial Pest Control",
  "Restaurant Pest Control",
  "Hotel Pest Control",
  "Termite Inspection",
  "Termite Treatment",
  "Pre Construction Termite Treatment",
  "Post Construction Termite Treatment",
  "Pest Inspection",
  "Pest Prevention",
  "Disinfection Treatment",

  // =======================================================
  // MOBILE PHONE
  // =======================================================

  "Mobile Sales",
  "Mobile Repair",
  "Mobile Servicing",
  "Mobile Screen Replacement",
  "Mobile Display Replacement",
  "Mobile Glass Replacement",
  "Mobile Battery Replacement",
  "Mobile Charging Port Repair",
  "Mobile Speaker Repair",
  "Mobile Mic Repair",
  "Mobile Camera Repair",
  "Mobile Button Repair",
  "Mobile Power Button Repair",
  "Mobile Volume Button Repair",
  "Mobile Motherboard Repair",
  "Mobile IC Repair",
  "Mobile Software Repair",
  "Mobile Software Update",
  "Mobile OS Installation",
  "Mobile Unlocking",
  "Mobile Data Recovery",
  "Mobile Water Damage Repair",
  "Mobile Back Panel Replacement",
  "Mobile Housing Replacement",
  "Mobile Accessories",
  "Mobile Cover",
  "Mobile Tempered Glass",
  "Mobile Charger",
  "Mobile Earphones",
  "Mobile Headphones",
  "Mobile Power Bank",
  "SIM Replacement",
  "SIM Activation",
  "Mobile Data Transfer",

  // =======================================================
  // COMPUTER & LAPTOP
  // =======================================================

  "Computer Sales",
  "Computer Repair",
  "Computer Servicing",
  "Laptop Sales",
  "Laptop Repair",
  "Laptop Servicing",
  "Desktop Repair",
  "Desktop Assembly",
  "Computer Upgrade",
  "RAM Upgrade",
  "SSD Upgrade",
  "Hard Disk Replacement",
  "Laptop Battery Replacement",
  "Laptop Screen Replacement",
  "Laptop Keyboard Replacement",
  "Laptop Charging Repair",
  "Laptop Hinge Repair",
  "Laptop Motherboard Repair",
  "Laptop Fan Cleaning",
  "Computer Formatting",
  "Windows Installation",
  "Linux Installation",
  "Software Installation",
  "Driver Installation",
  "Antivirus Installation",
  "Virus Removal",
  "Data Recovery",
  "Data Backup",
  "Hard Disk Repair",
  "Printer Setup",
  "Printer Repair",
  "Scanner Repair",
  "Computer Networking",
  "WiFi Setup",
  "LAN Installation",
  "Router Installation",
  "Network Troubleshooting",
  "CCTV Computer Setup",

  // =======================================================
  // CCTV & SECURITY
  // =======================================================

  "CCTV Installation",
  "CCTV Repair",
  "CCTV Maintenance",
  "CCTV Camera Installation",
  "IP Camera Installation",
  "Dome Camera Installation",
  "Bullet Camera Installation",
  "PTZ Camera Installation",
  "Wireless CCTV Installation",
  "CCTV DVR Installation",
  "CCTV NVR Installation",
  "CCTV Hard Disk Installation",
  "CCTV Remote Viewing Setup",
  "CCTV Mobile Monitoring",
  "CCTV Configuration",
  "CCTV Cabling",
  "CCTV Camera Replacement",
  "CCTV DVR Repair",
  "CCTV NVR Repair",
  "Video Door Phone Installation",
  "Video Door Phone Repair",
  "Biometric Installation",
  "Biometric Repair",
  "Access Control Installation",
  "Access Control Repair",
  "Door Access System",
  "Attendance System Installation",
  "Alarm System Installation",
  "Alarm System Repair",
  "Security System Maintenance",
  "Fire Alarm Installation",
  "Fire Alarm Repair",
  "Smoke Detector Installation",
  "Security Camera Monitoring",

  // =======================================================
  // AUTOMOBILE / CAR
  // =======================================================

  "Car Repair",
  "Car Servicing",
  "Car Maintenance",
  "Car Inspection",
  "Car Washing",
  "Car Detailing",
  "Car Interior Cleaning",
  "Car Exterior Cleaning",
  "Car Polishing",
  "Car Waxing",
  "Car Ceramic Coating",
  "Car Paint Protection",
  "Car Dent Repair",
  "Car Denting",
  "Car Painting",
  "Car Body Repair",
  "Car Bumper Repair",
  "Car Glass Replacement",
  "Car Windshield Replacement",
  "Car Battery Replacement",
  "Car AC Repair",
  "Car AC Servicing",
  "Car Tyre Replacement",
  "Car Wheel Alignment",
  "Car Wheel Balancing",
  "Car Puncture Repair",
  "Car Engine Repair",
  "Car Engine Servicing",
  "Car Clutch Repair",
  "Car Brake Repair",
  "Car Suspension Repair",
  "Car Steering Repair",
  "Car Gearbox Repair",
  "Car Electrical Repair",
  "Car Diagnostic Service",
  "Car Oil Change",
  "Car Filter Replacement",
  "Car Insurance Assistance",
  "Car Roadside Assistance",
  "Car Towing Service",
  "Car Pickup & Drop",
  "Used Car Inspection",

  // =======================================================
  // BIKE / TWO WHEELER
  // =======================================================

  "Bike Repair",
  "Bike Servicing",
  "Bike Maintenance",
  "Bike Washing",
  "Bike Detailing",
  "Bike Polishing",
  "Bike Battery Replacement",
  "Bike Tyre Replacement",
  "Bike Puncture Repair",
  "Bike Engine Repair",
  "Bike Engine Servicing",
  "Bike Brake Repair",
  "Bike Clutch Repair",
  "Bike Chain Repair",
  "Bike Chain Replacement",
  "Bike Suspension Repair",
  "Bike Electrical Repair",
  "Bike Diagnostic Service",
  "Bike Oil Change",
  "Scooter Repair",
  "Scooter Servicing",
  "Electric Scooter Repair",
  "Electric Bike Repair",
  "Two Wheeler Towing",
  "Two Wheeler Roadside Assistance",

  // =======================================================
  // RESTAURANT / FOOD
  // =======================================================

  "Dine In",
  "Takeaway",
  "Home Delivery",
  "Food Delivery",
  "Order Online",
  "Family Dining",
  "Party Orders",
  "Catering Service",
  "Corporate Catering",
  "Wedding Catering",
  "Birthday Catering",
  "Event Catering",
  "Outdoor Catering",
  "Buffet Service",
  "Breakfast Service",
  "Lunch Service",
  "Dinner Service",
  "Late Night Food",
  "Parcel Service",
  "Food Packing",
  "Table Reservation",
  "Party Booking",
  "Private Dining",
  "Banquet Dining",
  "Bulk Food Orders",
  "Corporate Food Orders",
  "Tiffin Service",
  "Meal Subscription",
  "Cloud Kitchen Service",
  "Custom Food Orders",
  "Vegetarian Food",
  "Non Vegetarian Food",
  "Veg & Non Veg Food",
  "Fast Food",
  "Street Food",
  "Bakery Items",
  "Cake Orders",
  "Birthday Cake",
  "Wedding Cake",
  "Custom Cake",
  "Dessert Orders",
  "Biryani Orders",
  "Pizza Delivery",
  "Burger Delivery",
  "Chinese Food",
  "South Indian Food",
  "North Indian Food",
  "Mughlai Food",
  "Continental Food",

  // =======================================================
  // BAKERY / CAKE
  // =======================================================

  "Cake Making",
  "Custom Cake Making",
  "Birthday Cake",
  "Anniversary Cake",
  "Wedding Cake",
  "Designer Cake",
  "Photo Cake",
  "Theme Cake",
  "Eggless Cake",
  "Egg Cake",
  "Cupcake Making",
  "Pastry Making",
  "Cookies",
  "Bread Making",
  "Fresh Bread",
  "Bun Making",
  "Donut Making",
  "Dessert Making",
  "Chocolate Making",
  "Chocolate Gift Box",
  "Cake Decoration",
  "Cake Delivery",
  "Bakery Delivery",

  // =======================================================
  // SALON / BEAUTY
  // =======================================================

  "Hair Cut",
  "Hair Styling",
  "Hair Wash",
  "Hair Spa",
  "Hair Treatment",
  "Hair Coloring",
  "Hair Highlighting",
  "Hair Straightening",
  "Hair Smoothening",
  "Hair Keratin Treatment",
  "Hair Rebonding",
  "Hair Perming",
  "Hair Extensions",
  "Hair Fall Treatment",
  "Beard Styling",
  "Beard Trimming",
  "Moustache Styling",
  "Shaving",
  "Facial",
  "Cleanup",
  "De Tan",
  "Bleach",
  "Threading",
  "Eyebrow Threading",
  "Upper Lip Threading",
  "Waxing",
  "Full Body Waxing",
  "Manicure",
  "Pedicure",
  "Nail Art",
  "Nail Extension",
  "Makeup",
  "Bridal Makeup",
  "Party Makeup",
  "Engagement Makeup",
  "Reception Makeup",
  "HD Makeup",
  "Airbrush Makeup",
  "Hair Makeup Package",
  "Bridal Hair Styling",
  "Mehndi Service",
  "Bridal Mehndi",
  "Party Mehndi",
  "Skin Treatment",
  "Skin Care",
  "Acne Treatment",
  "Body Spa",
  "Head Massage",
  "Body Massage",

  // =======================================================
  // FITNESS / GYM
  // =======================================================

  "Weight Training",
  "Cardio Workout",
  "Personal Training",
  "Group Training",
  "Functional Training",
  "Strength Training",
  "Weight Loss Program",
  "Fat Loss Program",
  "Muscle Gain Program",
  "Body Building",
  "Fitness Training",
  "Fitness Assessment",
  "Diet Consultation",
  "Workout Planning",
  "Beginner Fitness Program",
  "Advanced Fitness Program",
  "Cross Training",
  "HIIT Training",
  "Circuit Training",
  "Core Training",
  "Mobility Training",
  "Flexibility Training",
  "Yoga Classes",
  "Power Yoga",
  "Meditation Classes",
  "Zumba Classes",
  "Aerobics Classes",
  "Dance Fitness",
  "Pilates Classes",
  "Women Fitness Program",
  "Senior Fitness Program",
  "Online Fitness Training",

  // =======================================================
  // HOTEL / ACCOMMODATION
  // =======================================================

  "AC Rooms",
  "Non AC Rooms",
  "Family Rooms",
  "Deluxe Rooms",
  "Executive Rooms",
  "Suite Rooms",
  "Budget Rooms",
  "Single Rooms",
  "Double Rooms",
  "Triple Rooms",
  "Room Service",
  "Housekeeping",
  "Laundry Service",
  "24 Hour Reception",
  "Online Booking",
  "Hotel Booking",
  "Early Check In",
  "Late Check Out",
  "Airport Pickup",
  "Airport Drop",
  "Parking",
  "WiFi",
  "Breakfast Service",
  "Restaurant Service",
  "Conference Hall",
  "Meeting Room",
  "Banquet Hall",
  "Wedding Hall",
  "Party Hall",
  "Swimming Pool",
  "Travel Assistance",
  "Tour Assistance",

  // =======================================================
  // DENTAL / HEALTHCARE
  // =======================================================

  "Dental Consultation",
  "Tooth Cleaning",
  "Dental Filling",
  "Root Canal Treatment",
  "Tooth Extraction",
  "Wisdom Tooth Removal",
  "Dental Crown",
  "Dental Bridge",
  "Dental Implant",
  "Braces Consultation",
  "Dental Braces",
  "Clear Aligners",
  "Teeth Whitening",
  "Dental X Ray",
  "Dentures",
  "Child Dental Care",
  "Gum Treatment",
  "Gum Disease Treatment",
  "Oral Examination",
  "Cosmetic Dentistry",
  "General Health Consultation",
  "Doctor Consultation",
  "Health Checkup",
  "Blood Test",
  "Diagnostic Testing",
  "Home Sample Collection",
  "Pharmacy Service",
  "Medicine Delivery",
  "Physiotherapy",
  "Home Physiotherapy",
  "Health Counselling",

  // =======================================================
  // LEGAL SERVICES
  // =======================================================

  "Legal Consultation",
  "Legal Advice",
  "Civil Case",
  "Criminal Case",
  "Property Dispute",
  "Family Dispute",
  "Divorce Case",
  "Marriage Registration",
  "Bail Application",
  "Court Representation",
  "Legal Documentation",
  "Agreement Drafting",
  "Property Documentation",
  "Property Registration",
  "Rent Agreement",
  "Sale Agreement",
  "Will Drafting",
  "Power of Attorney",
  "Legal Notice",
  "Consumer Case",
  "Cheque Bounce Case",
  "Labour Dispute",
  "Corporate Legal Service",
  "Business Registration",
  "Trademark Registration",
  "Copyright Registration",
  "Patent Assistance",
  "GST Legal Assistance",
  "Tax Legal Assistance",
  "RTI Assistance",
  "Notary Service",
  "Affidavit Service",

  // =======================================================
  // ACCOUNTING / FINANCE
  // =======================================================

  "Accounting Service",
  "Bookkeeping",
  "Tax Consultation",
  "Income Tax Filing",
  "GST Registration",
  "GST Filing",
  "GST Return Filing",
  "GST Consultation",
  "TDS Filing",
  "TDS Return",
  "Tax Planning",
  "Audit Service",
  "Internal Audit",
  "Financial Planning",
  "Business Accounting",
  "Payroll Service",
  "Salary Processing",
  "Invoice Management",
  "Billing Service",
  "Company Registration",
  "Firm Registration",
  "MSME Registration",
  "Udyam Registration",
  "Startup Registration",
  "Import Export Registration",
  "Digital Signature",
  "PAN Application",
  "TAN Application",
  "Business Loan Assistance",
  "Loan Documentation",
  "Insurance Assistance",

  // =======================================================
  // PRINTING
  // =======================================================

  "Visiting Card Printing",
  "Business Card Printing",
  "Wedding Card Printing",
  "Invitation Card Printing",
  "Birthday Card Printing",
  "Flex Printing",
  "Banner Printing",
  "Poster Printing",
  "Pamphlet Printing",
  "Flyer Printing",
  "Brochure Printing",
  "Catalogue Printing",
  "Offset Printing",
  "Digital Printing",
  "Screen Printing",
  "Photo Printing",
  "Large Format Printing",
  "Vinyl Printing",
  "Sticker Printing",
  "Label Printing",
  "Packaging Printing",
  "Box Printing",
  "Calendar Printing",
  "Diary Printing",
  "Bill Book Printing",
  "Letterhead Printing",
  "Envelope Printing",
  "Receipt Printing",
  "Menu Card Printing",
  "Book Printing",
  "Magazine Printing",
  "Newspaper Printing",
  "ID Card Printing",
  "Certificate Printing",
  "T Shirt Printing",
  "Mug Printing",
  "Photo Frame Printing",
  "Sign Board Printing",
  "Glow Sign Board",
  "LED Sign Board",
  "Acrylic Sign Board",
  "Name Plate Making",

  // =======================================================
  // PHOTOGRAPHY / VIDEO
  // =======================================================

  "Wedding Photography",
  "Wedding Videography",
  "Pre Wedding Photography",
  "Pre Wedding Videography",
  "Birthday Photography",
  "Birthday Videography",
  "Event Photography",
  "Event Videography",
  "Corporate Photography",
  "Corporate Videography",
  "Product Photography",
  "Product Videography",
  "Fashion Photography",
  "Model Photography",
  "Portfolio Photography",
  "Food Photography",
  "Real Estate Photography",
  "Property Photography",
  "Drone Photography",
  "Drone Videography",
  "Cinematic Video",
  "Live Streaming",
  "Video Editing",
  "Photo Editing",
  "Album Designing",
  "Wedding Album",
  "Photo Printing",
  "Studio Photography",
  "Passport Photo",
  "ID Photo",
  "Maternity Photography",
  "Baby Photography",
  "Newborn Photography",
  "Couple Photography",

  // =======================================================
  // DIGITAL / IT SERVICES
  // =======================================================

  "Website Design",
  "Website Development",
  "Ecommerce Website",
  "Business Website",
  "Landing Page Design",
  "Web Application Development",
  "Mobile App Development",
  "Android App Development",
  "iOS App Development",
  "Software Development",
  "Custom Software Development",
  "CRM Development",
  "ERP Development",
  "POS Software",
  "Billing Software",
  "Inventory Software",
  "School Management Software",
  "Hospital Management Software",
  "Hotel Management Software",
  "Digital Marketing",
  "Search Engine Optimization",
  "Local SEO",
  "Google Business Profile Setup",
  "Social Media Marketing",
  "Social Media Management",
  "Facebook Advertising",
  "Instagram Marketing",
  "Google Ads",
  "Online Advertising",
  "Content Marketing",
  "Content Writing",
  "Copywriting",
  "Graphic Design",
  "Logo Design",
  "Branding Service",
  "UI UX Design",
  "Domain Registration",
  "Web Hosting",
  "Email Hosting",
  "SSL Installation",
  "Website Maintenance",
  "Website Security",
  "Data Backup",
  "Cloud Setup",
  "IT Support",
  "Technical Support",
  "Computer Networking",

  // =======================================================
  // EDUCATION / TRAINING
  // =======================================================

  "Home Tuition",
  "Online Tuition",
  "School Tuition",
  "College Tuition",
  "Maths Tuition",
  "Science Tuition",
  "English Tuition",
  "Hindi Tuition",
  "Computer Classes",
  "Spoken English",
  "Personality Development",
  "Competitive Exam Coaching",
  "Government Exam Coaching",
  "SSC Coaching",
  "Bank Exam Coaching",
  "Railway Exam Coaching",
  "UPSC Coaching",
  "BPSC Coaching",
  "NEET Coaching",
  "JEE Coaching",
  "Commerce Coaching",
  "Accounting Classes",
  "Tally Training",
  "Programming Classes",
  "Web Development Training",
  "Digital Marketing Training",
  "Graphic Design Training",
  "Computer Training",
  "Vocational Training",
  "Skill Development Training",
  "Music Classes",
  "Dance Classes",
  "Drawing Classes",
  "Art Classes",
  "Language Classes",

  // =======================================================
  // EVENT SERVICES
  // =======================================================

  "Event Planning",
  "Event Management",
  "Wedding Planning",
  "Wedding Decoration",
  "Birthday Decoration",
  "Party Decoration",
  "Corporate Event Management",
  "Stage Decoration",
  "Stage Setup",
  "Balloon Decoration",
  "Flower Decoration",
  "Theme Decoration",
  "Lighting Decoration",
  "DJ Service",
  "Sound System",
  "Live Music",
  "Band Service",
  "Anchor Service",
  "Host Service",
  "Catering Service",
  "Tent House Service",
  "Furniture Rental",
  "Table Rental",
  "Chair Rental",
  "Generator Rental",
  "Event Equipment Rental",
  "Wedding Invitation Design",
  "Wedding Coordination",
  "Mehndi Artist",
  "Makeup Artist",
  "Photobooth Service",
  "Fireworks Decoration",

  // =======================================================
  // TRAVEL / TOURISM
  // =======================================================

  "Travel Booking",
  "Flight Booking",
  "Train Ticket Booking",
  "Bus Ticket Booking",
  "Hotel Booking",
  "Holiday Package",
  "Tour Package",
  "Honeymoon Package",
  "Family Tour Package",
  "Corporate Tour Package",
  "Group Tour Package",
  "Pilgrimage Tour",
  "Adventure Tour",
  "Local Sightseeing",
  "Tour Guide",
  "Travel Consultation",
  "Visa Assistance",
  "Passport Assistance",
  "Travel Insurance",
  "Car Rental",
  "Taxi Service",
  "Airport Taxi",
  "Outstation Taxi",
  "Local Taxi",
  "Tempo Traveller",
  "Bus Rental",
  "Tourist Vehicle Rental",

  // =======================================================
  // COURIER / LOGISTICS
  // =======================================================

  "Courier Service",
  "Local Courier",
  "Domestic Courier",
  "International Courier",
  "Document Courier",
  "Parcel Delivery",
  "Same Day Delivery",
  "Express Delivery",
  "Doorstep Delivery",
  "Pickup & Delivery",
  "Cargo Service",
  "Freight Service",
  "Transport Service",
  "Goods Transport",
  "Truck Transport",
  "Mini Truck Service",
  "Tempo Transport",
  "Warehouse Service",
  "Warehousing",
  "Storage Service",
  "Packing Service",
  "Moving Service",
  "House Shifting",
  "Office Shifting",
  "Furniture Shifting",
  "Loading Service",
  "Unloading Service",
  "Packing & Moving",
  "Logistics Management",
  "Supply Chain Service",

  // =======================================================
  // REAL ESTATE
  // =======================================================

  "Property Sale",
  "Property Purchase",
  "Property Rental",
  "Property Leasing",
  "Residential Property",
  "Commercial Property",
  "Industrial Property",
  "Land Sale",
  "Plot Sale",
  "Flat Sale",
  "Apartment Sale",
  "House Sale",
  "Villa Sale",
  "Office Sale",
  "Shop Sale",
  "Warehouse Sale",
  "Property Valuation",
  "Property Consultation",
  "Property Documentation",
  "Property Verification",
  "Property Registration Assistance",
  "Rental Property",
  "Tenant Verification",
  "Property Management",
  "Real Estate Investment",
  "Home Loan Assistance",

  // =======================================================
  // INTERIOR / CONSTRUCTION
  // =======================================================

  "Interior Design",
  "Home Interior Design",
  "Office Interior Design",
  "Commercial Interior Design",
  "Kitchen Interior Design",
  "Bedroom Interior Design",
  "Living Room Interior",
  "Bathroom Interior",
  "Modular Kitchen",
  "Modular Wardrobe",
  "False Ceiling",
  "Gypsum Ceiling",
  "POP Ceiling",
  "PVC Ceiling",
  "Wooden Ceiling",
  "Wall Paneling",
  "Wallpaper Installation",
  "Flooring Installation",
  "Tile Installation",
  "Marble Installation",
  "Granite Installation",
  "Vinyl Flooring",
  "Wooden Flooring",
  "Electrical Interior Work",
  "Plumbing Interior Work",
  "Renovation Work",
  "Home Renovation",
  "Office Renovation",
  "Civil Construction",
  "Residential Construction",
  "Commercial Construction",
  "Building Construction",
  "House Construction",
  "Boundary Wall Construction",
  "Roof Construction",
  "Concrete Work",
  "Brick Work",
  "Plastering Work",
  "Waterproofing Work",

  // =======================================================
  // SECURITY SERVICES
  // =======================================================

  "Security Guard Service",
  "Security Agency",
  "Home Security",
  "Office Security",
  "Industrial Security",
  "Event Security",
  "Personal Security",
  "Bouncer Service",
  "Bodyguard Service",
  "Night Security",
  "Day Security",
  "Security Supervisor",
  "Security Training",
  "CCTV Monitoring",
  "Alarm Monitoring",
  "Access Control",
  "Visitor Management",
  "Security Audit",

  // =======================================================
  // BEAUTY / PERSONAL CARE
  // =======================================================

  "Personal Grooming",
  "Beauty Consultation",
  "Skin Consultation",
  "Hair Consultation",
  "Bridal Package",
  "Beauty Package",
  "Spa Package",
  "Hair Care Package",
  "Skin Care Package",
  "Nail Care",
  "Body Care",
  "Men Grooming",
  "Women Grooming",
  "Kids Haircut",
  "Kids Grooming",

  // =======================================================
  // LAUNDRY
  // =======================================================

  "Laundry Service",
  "Dry Cleaning",
  "Clothes Washing",
  "Clothes Ironing",
  "Steam Ironing",
  "Saree Dry Cleaning",
  "Suit Dry Cleaning",
  "Blanket Cleaning",
  "Carpet Dry Cleaning",
  "Curtain Dry Cleaning",
  "Shoe Cleaning",
  "Bag Cleaning",
  "Leather Cleaning",
  "Laundry Pickup",
  "Laundry Delivery",
  "Express Laundry",
  "Commercial Laundry",

  // =======================================================
  // REPAIR / APPLIANCES
  // =======================================================

  "Washing Machine Repair",
  "Washing Machine Servicing",
  "Refrigerator Repair",
  "Refrigerator Servicing",
  "Microwave Repair",
  "Microwave Servicing",
  "Geyser Repair",
  "Geyser Installation",
  "Geyser Servicing",
  "Water Purifier Repair",
  "RO Installation",
  "RO Repair",
  "RO Servicing",
  "RO Filter Replacement",
  "TV Repair",
  "LED TV Repair",
  "LCD TV Repair",
  "Smart TV Repair",
  "Home Appliance Repair",
  "Kitchen Appliance Repair",
  "Mixer Grinder Repair",
  "Induction Cooktop Repair",
  "Chimney Repair",
  "Chimney Installation",
  "Chimney Servicing",
  "Gas Stove Repair",
  "Gas Stove Installation",

  // =======================================================
  // SOLAR
  // =======================================================

  "Solar Panel Installation",
  "Solar Panel Cleaning",
  "Solar Panel Maintenance",
  "Solar Inverter Installation",
  "Solar Battery Installation",
  "Solar Battery Replacement",
  "Solar Water Heater Installation",
  "Solar Water Heater Repair",
  "Solar System Inspection",
  "Solar System Repair",
  "Rooftop Solar Installation",
  "Commercial Solar Installation",
  "Residential Solar Installation",
  "Solar Consultation",
  "Solar Subsidy Assistance",

  // =======================================================
  // WATER / PURIFICATION
  // =======================================================

  "Water Purifier Installation",
  "Water Purifier Repair",
  "Water Purifier Servicing",
  "RO Installation",
  "RO Repair",
  "RO Maintenance",
  "RO Filter Replacement",
  "RO Membrane Replacement",
  "Water Filter Installation",
  "Water Softener Installation",
  "Water Softener Maintenance",
  "Water Quality Testing",
  "Drinking Water Testing",
  "Water Treatment",
  "Water Treatment Plant",
  "Water Tank Cleaning",
  "Water Tank Repair",

  // =======================================================
  // AGRICULTURE
  // =======================================================

  "Agricultural Equipment Repair",
  "Tractor Repair",
  "Tractor Servicing",
  "Tractor Rental",
  "Farm Equipment Rental",
  "Irrigation Installation",
  "Drip Irrigation",
  "Sprinkler Irrigation",
  "Borewell Service",
  "Borewell Drilling",
  "Tube Well Installation",
  "Pump Installation",
  "Agricultural Pump Repair",
  "Crop Consultation",
  "Agriculture Consultation",
  "Soil Testing",
  "Water Testing",
  "Farm Land Preparation",
  "Pesticide Spraying",
  "Fertilizer Application",

  // =======================================================
  // PET SERVICES
  // =======================================================

  "Pet Grooming",
  "Dog Grooming",
  "Cat Grooming",
  "Pet Bathing",
  "Pet Hair Cutting",
  "Pet Nail Trimming",
  "Pet Boarding",
  "Pet Day Care",
  "Pet Training",
  "Dog Training",
  "Pet Walking",
  "Pet Sitting",
  "Pet Taxi",
  "Pet Food Delivery",
  "Pet Consultation",
  "Veterinary Consultation",
  "Pet Vaccination",
  "Pet Health Checkup",

  // =======================================================
  // MOVERS / PACKERS
  // =======================================================

  "House Shifting",
  "Office Shifting",
  "Local Shifting",
  "Intercity Shifting",
  "Vehicle Transportation",
  "Car Transportation",
  "Bike Transportation",
  "Furniture Transportation",
  "Packing Service",
  "Unpacking Service",
  "Loading Service",
  "Unloading Service",
  "Moving Boxes",
  "Storage Service",
  "Warehouse Storage",
  "Moving Insurance",
  "Relocation Service",

  // =======================================================
  // GENERAL RENTAL
  // =======================================================

  "Equipment Rental",
  "Machine Rental",
  "Generator Rental",
  "Car Rental",
  "Bike Rental",
  "Furniture Rental",
  "Chair Rental",
  "Table Rental",
  "Tent Rental",
  "Sound System Rental",
  "Lighting Rental",
  "Camera Rental",
  "Projector Rental",
  "Event Equipment Rental",
  "Construction Equipment Rental",
  "Crane Rental",
  "JCB Rental",
  "Excavator Rental",
  "Tractor Rental",

  // =======================================================
  // BUSINESS SUPPORT
  // =======================================================

  "Business Registration",
  "Business Consultation",
  "Startup Consultation",
  "Business Plan Preparation",
  "Market Research",
  "Market Survey",
  "Franchise Consultation",
  "Digital Business Setup",
  "Online Business Setup",
  "Business Listing",
  "Lead Generation",
  "Customer Support",
  "Call Center Service",
  "Telecalling Service",
  "Data Entry",
  "Back Office Service",
  "Document Digitization",
  "Document Scanning",
  "Photocopy Service",
  "Scanning Service",
  "Lamination Service",
  "Binding Service",

  // =======================================================
  // GENERAL DOCUMENT SERVICES
  // =======================================================

  "Document Printing",
  "Document Scanning",
  "Photocopy",
  "Color Photocopy",
  "Black & White Photocopy",
  "Lamination",
  "Spiral Binding",
  "Hard Binding",
  "Soft Binding",
  "Document Binding",
  "Online Form Filling",
  "Application Form Filling",
  "Resume Writing",
  "Resume Designing",
  "CV Writing",
  "CV Designing",
  "Document Typing",
  "Hindi Typing",
  "English Typing",
  "Translation Service",
  "Document Translation",
  "Certificate Assistance",

  // =======================================================
  // MISCELLANEOUS
  // =======================================================

  "Gift Delivery",
  "Flower Delivery",
  "Bouquet Making",
  "Gift Packing",
  "Custom Gift",
  "Corporate Gifts",
  "Personalized Gifts",
  "Photo Gifts",
  "Key Making",
  "Lock Repair",
  "Lock Installation",
  "Door Lock Repair",
  "Digital Lock Installation",
  "Safe Lock Repair",
  "Pest Inspection",
  "Property Inspection",
  "Home Inspection",
  "Safety Inspection",
  "Fire Safety Inspection",
  "Fire Extinguisher Refill",
  "Fire Extinguisher Installation",
  "Fire Safety Training",
  "Emergency Assistance",
  "Pickup & Drop Service",
  "Doorstep Assistance",

];

// =========================================================
// OPTIONAL: NORMALIZED UNIQUE LIBRARY
// =========================================================

export const UNIQUE_SERVICE_LIBRARY = [
  ...new Map(
    SERVICE_LIBRARY.map((service) => [
      service.trim().toLowerCase(),
      service.trim(),
    ])
  ).values(),
];

// =========================================================
// DEFAULT EXPORT
// =========================================================

export default UNIQUE_SERVICE_LIBRARY;